-- V1: Initial schema for CV service
-- All tables use UUID primary keys generated by gen_random_uuid().
-- Timestamps default to now() and are updated via Hibernate @UpdateTimestamp.

-- GeneralInfo: single-row table (enforced at application layer via findFirst()/upsert).
CREATE TABLE general_info (
    id                  UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    first_name          VARCHAR(255),
    last_name           VARCHAR(255),
    marital_status      VARCHAR(100),
    number_of_children  INTEGER,
    date_of_birth       DATE,
    place_of_birth      VARCHAR(255),
    nationality         VARCHAR(255),
    image_url           TEXT,
    summary             TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ProfessionalExperience
CREATE TABLE professional_experience (
    id           UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    title        VARCHAR(255) NOT NULL,
    company_name VARCHAR(255) NOT NULL,
    start_date   DATE        NOT NULL,
    end_date     DATE,
    location     VARCHAR(255),
    description  TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Education
CREATE TABLE education (
    id          UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    school_name VARCHAR(255) NOT NULL,
    start_date  DATE        NOT NULL,
    end_date    DATE,
    location    VARCHAR(255),
    description TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Skill (level 1–10)
CREATE TABLE skill (
    id         UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    title      VARCHAR(255) NOT NULL,
    level      INTEGER     NOT NULL CHECK (level BETWEEN 1 AND 10),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Competence
CREATE TABLE competence (
    id          UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    description TEXT        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Language (level 1–10)
CREATE TABLE language (
    id         UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    level      INTEGER     NOT NULL CHECK (level BETWEEN 1 AND 10),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Hobby
CREATE TABLE hobby (
    id         UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
